### ISSUE TITLE
llama user to join chat room not working

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-llama-plugin#4]
Dele,

First : congrats for llama integration, it works perfectly ! We just need to use the mistral instruct version of LLM DB.

Btw i wonder if we can make llama user responding as a regular user when it joins a chat room. Nice to have maybe, no clue what size the effort is, what do you think ?

![screenshot18](https://github.com/igniterealtime/openfire-llama-plugin/assets/29485972/12fdd618-37d1-4adb-a1a3-007ac0d4070e)

**Comment by deleolajide** [comment]
LLaMA has support for groupchat.  It had a bug that prevented it for working. It can be invited and will auto accept and join.

It will ignore messages until you type a message that starts its name (llama default). Then it will respond. here is an example using llama@pade.chat

![image](https://github.com/igniterealtime/openfire-llama-plugin/assets/110731/f5f59014-d7ec-45d3-846a-97d20c8b628e)

Notice it ignored the **that was cool** message

Also if the chat is hosted locally, it will auto join and respond if any message from the chat room starts with its name

**Comment by ClaudeStabile** [comment]
Excellent The Saint !!! Impressed.
That's magic it breaks the limits
Congrats for that

**Comment by ClaudeStabile** [comment]
The only big problem i have is that LLAMA is named LLAMA so when i try to contact him in vocal it is impossible to get llama with 2 "ll" transcribed :) but that's OK i can probably rename the default user as Albert to fix, i will try out on another server
